# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cashier.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cashier(object):
    def setupUi(self, Cashier):
        Cashier.setObjectName("Cashier")
        Cashier.resize(985, 649)
        Cashier.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Cashier)
        self.centralwidget.setStyleSheet("background-color:#ffffff;")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftmenu = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftmenu.sizePolicy().hasHeightForWidth())
        self.leftmenu.setSizePolicy(sizePolicy)
        self.leftmenu.setMinimumSize(QtCore.QSize(150, 0))
        self.leftmenu.setStyleSheet("background-color:#374550;\n"
"")
        self.leftmenu.setObjectName("leftmenu")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.leftmenu)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_5 = QtWidgets.QFrame(self.leftmenu)
        self.frame_5.setStyleSheet("background: transparent;\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setStyleSheet("background: transparent;\n"
"")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-menu-25.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_12.addWidget(self.pushButton, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout_11.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.leftmenu)
        self.frame_4.setStyleSheet("background: transparent;\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(self.frame_4)
        self.logo.setMaximumSize(QtCore.QSize(135, 80))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../cashier/Cashier Interface/JJLOGO.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.JJelevate_text = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.JJelevate_text.setFont(font)
        self.JJelevate_text.setStyleSheet("color: #f6f3ee; ")
        self.JJelevate_text.setScaledContents(True)
        self.JJelevate_text.setObjectName("JJelevate_text")
        self.verticalLayout.addWidget(self.JJelevate_text)
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_11.addWidget(self.frame_4)
        self.btnDashboard = QtWidgets.QPushButton(self.leftmenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 5px;\n"
"font-size: 12;\n"
"font-family: \"Verdana\", sans-serif; \n"
"text-align: left;}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color:#8d2721;\n"
"color:white;\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("dashboard_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDashboard.setIcon(icon1)
        self.btnDashboard.setIconSize(QtCore.QSize(25, 25))
        self.btnDashboard.setObjectName("btnDashboard")
        self.verticalLayout_11.addWidget(self.btnDashboard)
        spacerItem1 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem1)
        self.btnInventory = QtWidgets.QPushButton(self.leftmenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.btnInventory.setFont(font)
        self.btnInventory.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 5px;\n"
"font-size: 12;\n"
"font-family: \"Verdana\", sans-serif; \n"
"text-align: left;}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color:#8d2721;\n"
"color:white;\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("inventory_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInventory.setIcon(icon2)
        self.btnInventory.setIconSize(QtCore.QSize(25, 25))
        self.btnInventory.setObjectName("btnInventory")
        self.verticalLayout_11.addWidget(self.btnInventory)
        spacerItem2 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem2)
        self.btnOrders = QtWidgets.QPushButton(self.leftmenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.btnOrders.setFont(font)
        self.btnOrders.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 5px;\n"
"font-size: 12;\n"
"font-family: \"Verdana\", sans-serif; \n"
"text-align: left;}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color:#8d2721;\n"
"color:white;\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("orders_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOrders.setIcon(icon3)
        self.btnOrders.setIconSize(QtCore.QSize(25, 25))
        self.btnOrders.setObjectName("btnOrders")
        self.verticalLayout_11.addWidget(self.btnOrders)
        spacerItem3 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem3)
        self.btnSales = QtWidgets.QPushButton(self.leftmenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.btnSales.setFont(font)
        self.btnSales.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 5px;\n"
"font-size: 12;\n"
"font-family: \"Verdana\", sans-serif; \n"
"text-align: left;}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color:#8d2721;\n"
"color:white;\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("sales_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSales.setIcon(icon4)
        self.btnSales.setIconSize(QtCore.QSize(25, 25))
        self.btnSales.setObjectName("btnSales")
        self.verticalLayout_11.addWidget(self.btnSales)
        spacerItem4 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem4)
        self.btnAccount = QtWidgets.QPushButton(self.leftmenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.btnAccount.setFont(font)
        self.btnAccount.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 5px;\n"
"font-size: 12;\n"
"font-family: \"Verdana\", sans-serif; \n"
"text-align: left;}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color:#8d2721;\n"
"color:white;\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("account_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAccount.setIcon(icon5)
        self.btnAccount.setIconSize(QtCore.QSize(25, 25))
        self.btnAccount.setObjectName("btnAccount")
        self.verticalLayout_11.addWidget(self.btnAccount)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem5)
        self.btnLogout = QtWidgets.QPushButton(self.leftmenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.btnLogout.setFont(font)
        self.btnLogout.setStyleSheet("/* Default Inactive Buttons */\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 15px;\n"
"border: 1px solid #000000; \n"
"    padding: 5px;\n"
"font-size: 12;\n"
"font-family: \"Verdana\", sans-serif; \n"
"text-align: left;}\n"
"\n"
"/* Hover Effect on Inactive Buttons */\n"
"QPushButton:hover {\n"
"    background-color:#8d2721;\n"
"color:white;\n"
"}\n"
"\n"
"/* Active Button (Current Page) */\n"
"QPushButton#activeButton {\n"
"    background-color: #8d2721;\n"
"    color: white;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("logout_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogout.setIcon(icon6)
        self.btnLogout.setIconSize(QtCore.QSize(25, 25))
        self.btnLogout.setObjectName("btnLogout")
        self.verticalLayout_11.addWidget(self.btnLogout)
        self.horizontalLayout.addWidget(self.leftmenu)
        self.tabs = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setObjectName("tabs")
        self.pageDashboard = QtWidgets.QWidget()
        self.pageDashboard.setObjectName("pageDashboard")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageDashboard)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QWidget(self.pageDashboard)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dateday = QtWidgets.QWidget(self.header)
        self.dateday.setStyleSheet("")
        self.dateday.setObjectName("dateday")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.dateday)
        self.horizontalLayout_3.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.realdateday = QtWidgets.QLabel(self.dateday)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.realdateday.setFont(font)
        self.realdateday.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.realdateday.setObjectName("realdateday")
        self.horizontalLayout_3.addWidget(self.realdateday, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.dateday)
        self.time = QtWidgets.QWidget(self.header)
        self.time.setObjectName("time")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.time)
        self.horizontalLayout_4.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.realtime = QtWidgets.QLabel(self.time)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.realtime.setFont(font)
        self.realtime.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border: 1px solid black;\n"
"    padding: 12px;\n"
"    text-align: center;\n"
"}\n"
"")
        self.realtime.setObjectName("realtime")
        self.horizontalLayout_4.addWidget(self.realtime, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.time)
        self.verticalLayout_2.addWidget(self.header, 0, QtCore.Qt.AlignTop)
        self.records = QtWidgets.QWidget(self.pageDashboard)
        self.records.setStyleSheet("QWidget{\n"
"background: transparent;}\n"
"\n"
"\n"
"#orderss {\n"
"    background-color: white;\n"
"    border: 1px solid black;\n"
"    border-radius: 15;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"#saless {\n"
"    background-color: white;\n"
"    border: 1px solid black;\n"
"    border-radius: 15;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"#revenue {\n"
"    background-color: white;\n"
"    border: 1px solid black;\n"
"    border-radius: 15;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.records.setObjectName("records")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.records)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.saless = QtWidgets.QFrame(self.records)
        self.saless.setStyleSheet("\n"
"")
        self.saless.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saless.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saless.setObjectName("saless")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.saless)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(self.saless)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setMaximumSize(QtCore.QSize(50, 40))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("moneyhand_icon.svg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#c9cc7f;\n"
"font-family: \"MS Shell Dlg 2\", sans-serif;\n"
"background: transparent;\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMaximumSize(QtCore.QSize(45, 30))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("up.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.verticalLayout_5.addWidget(self.frame)
        self.label_5 = QtWidgets.QLabel(self.saless)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #004aad;\n"
"font-family: \'Poppins\', Medium;\n"
"background: transparent;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addWidget(self.saless)
        self.orderss = QtWidgets.QFrame(self.records)
        self.orderss.setStyleSheet("")
        self.orderss.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.orderss.setFrameShadow(QtWidgets.QFrame.Raised)
        self.orderss.setObjectName("orderss")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.orderss)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.orderss)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setMaximumSize(QtCore.QSize(50, 40))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("moneyhand_icon.svg"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:#c9cc7f;\n"
"font-family: \"MS Shell Dlg 2\", sans-serif;\n"
"background: transparent;\n"
"")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setMaximumSize(QtCore.QSize(45, 30))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("up.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.label_7 = QtWidgets.QLabel(self.orderss)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #004aad;\n"
"font-family: \'Poppins\', Medium;\n"
"background: transparent;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addWidget(self.orderss)
        self.revenue = QtWidgets.QFrame(self.records)
        self.revenue.setStyleSheet("")
        self.revenue.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.revenue.setFrameShadow(QtWidgets.QFrame.Raised)
        self.revenue.setObjectName("revenue")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.revenue)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.revenue)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setMaximumSize(QtCore.QSize(50, 40))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("moneyhand_icon.svg"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:#c9cc7f;\n"
"font-family: \"MS Shell Dlg 2\", sans-serif;\n"
"background: transparent;\n"
"")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19, 0, QtCore.Qt.AlignHCenter)
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setMaximumSize(QtCore.QSize(45, 30))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("up.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.label_14 = QtWidgets.QLabel(self.revenue)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: #004aad;\n"
"font-family: \'Poppins\', Medium;\n"
"background: transparent;")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addWidget(self.revenue)
        self.verticalLayout_2.addWidget(self.records)
        self.graph = QtWidgets.QWidget(self.pageDashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph.sizePolicy().hasHeightForWidth())
        self.graph.setSizePolicy(sizePolicy)
        self.graph.setStyleSheet("QWidget{\n"
"background: transparent;}\n"
"\n"
"\n"
"#bestSell {\n"
"    background-color: white;\n"
"    border: 1px solid black;\n"
"    border-radius: 15;\n"
"    padding: 10px;\n"
"}\n"
"#Inventory{\n"
"    background-color: white;\n"
"    border: 1px solid black;\n"
"    border-radius: 15;\n"
"    padding: 10px;\n"
"}")
        self.graph.setObjectName("graph")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.graph)
        self.horizontalLayout_11.setContentsMargins(0, 5, 0, 6)
        self.horizontalLayout_11.setSpacing(20)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.bestSell = QtWidgets.QFrame(self.graph)
        self.bestSell.setStyleSheet("")
        self.bestSell.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bestSell.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bestSell.setObjectName("bestSell")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.bestSell)
        self.verticalLayout_9.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_21 = QtWidgets.QLabel(self.bestSell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setStyleSheet("")
        self.label_21.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_9.addWidget(self.label_21)
        self.chart = QtWidgets.QFrame(self.bestSell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chart.sizePolicy().hasHeightForWidth())
        self.chart.setSizePolicy(sizePolicy)
        self.chart.setStyleSheet("background-color: white;\n"
"border: none;\n"
"")
        self.chart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chart.setObjectName("chart")
        self.verticalLayout_9.addWidget(self.chart)
        self.ViewSalesbtn = QtWidgets.QPushButton(self.bestSell)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setUnderline(True)
        self.ViewSalesbtn.setFont(font)
        self.ViewSalesbtn.setStyleSheet("QPushButton{color: blue;\n"
"font-family: \'Poppins\', Medium;\n"
"text-decoration: underline;\n"
"border: none;\n"
"background: transparent;}\n"
"QPushButton:hover {\n"
"color:#8d2721;\n"
"}\n"
"")
        self.ViewSalesbtn.setObjectName("ViewSalesbtn")
        self.verticalLayout_9.addWidget(self.ViewSalesbtn)
        self.horizontalLayout_11.addWidget(self.bestSell)
        self.Inventory = QtWidgets.QFrame(self.graph)
        self.Inventory.setStyleSheet("#p1,#p2,#p3,#p4{\n"
"    border: none;\n"
"    border-bottom: 1px dotted black;\n"
"}\n"
"")
        self.Inventory.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Inventory.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Inventory.setObjectName("Inventory")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Inventory)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.inventorylabel = QtWidgets.QLabel(self.Inventory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inventorylabel.sizePolicy().hasHeightForWidth())
        self.inventorylabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.inventorylabel.setFont(font)
        self.inventorylabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inventorylabel.setStyleSheet("")
        self.inventorylabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.inventorylabel.setObjectName("inventorylabel")
        self.verticalLayout_10.addWidget(self.inventorylabel)
        self.alertframe = QtWidgets.QFrame(self.Inventory)
        self.alertframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.alertframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alertframe.setObjectName("alertframe")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.alertframe)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lowstock = QtWidgets.QLabel(self.alertframe)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lowstock.setFont(font)
        self.lowstock.setObjectName("lowstock")
        self.horizontalLayout_12.addWidget(self.lowstock, 0, QtCore.Qt.AlignLeft)
        self.label_24 = QtWidgets.QLabel(self.alertframe)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: #d75413;\n"
"background: transparent;")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_12.addWidget(self.label_24, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.addWidget(self.alertframe)
        self.label_25 = QtWidgets.QLabel(self.Inventory)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_25.setStyleSheet("color: #000000;\n"
"border: 1px solid #000000; \n"
"border-radius: 7px; \n"
"padding: 3px; \n"
"background-color: #fff2bd; \n"
"")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_10.addWidget(self.label_25)
        self.p1 = QtWidgets.QFrame(self.Inventory)
        self.p1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p1.setObjectName("p1")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.p1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_22 = QtWidgets.QLabel(self.p1)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_13.addWidget(self.label_22)
        self.label_28 = QtWidgets.QLabel(self.p1)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: #b2423c;\n"
"background: transparent;")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_13.addWidget(self.label_28, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.addWidget(self.p1)
        self.p2 = QtWidgets.QFrame(self.Inventory)
        self.p2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p2.setObjectName("p2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.p2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_27 = QtWidgets.QLabel(self.p2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_14.addWidget(self.label_27, 0, QtCore.Qt.AlignLeft)
        self.label_29 = QtWidgets.QLabel(self.p2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: #b2423c;\n"
"background: transparent;")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_14.addWidget(self.label_29, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.addWidget(self.p2)
        self.p3 = QtWidgets.QFrame(self.Inventory)
        self.p3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p3.setObjectName("p3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.p3)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_23 = QtWidgets.QLabel(self.p3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_15.addWidget(self.label_23, 0, QtCore.Qt.AlignLeft)
        self.label_30 = QtWidgets.QLabel(self.p3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: #b2423c;\n"
"background: transparent;")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_15.addWidget(self.label_30, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.addWidget(self.p3)
        self.p4 = QtWidgets.QFrame(self.Inventory)
        self.p4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p4.setObjectName("p4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.p4)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_26 = QtWidgets.QLabel(self.p4)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_16.addWidget(self.label_26, 0, QtCore.Qt.AlignLeft)
        self.label_31 = QtWidgets.QLabel(self.p4)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: #b2423c;\n"
"background: transparent;")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_16.addWidget(self.label_31, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.addWidget(self.p4)
        self.ViewSalesbtn_2 = QtWidgets.QPushButton(self.Inventory)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setUnderline(True)
        self.ViewSalesbtn_2.setFont(font)
        self.ViewSalesbtn_2.setStyleSheet("QPushButton{color: blue;\n"
"font-family: \'Poppins\', Medium;\n"
"text-decoration: underline;\n"
"border: none;\n"
"background: transparent;}\n"
"QPushButton:hover {\n"
"color:#8d2721;\n"
"}\n"
"")
        self.ViewSalesbtn_2.setObjectName("ViewSalesbtn_2")
        self.verticalLayout_10.addWidget(self.ViewSalesbtn_2)
        self.horizontalLayout_11.addWidget(self.Inventory)
        self.verticalLayout_2.addWidget(self.graph)
        self.tabs.addWidget(self.pageDashboard)
        self.pageInventory = QtWidgets.QWidget()
        self.pageInventory.setObjectName("pageInventory")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageInventory)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.inv = QtWidgets.QLabel(self.pageInventory)
        self.inv.setObjectName("inv")
        self.verticalLayout_3.addWidget(self.inv)
        self.tabs.addWidget(self.pageInventory)
        self.pageOrder = QtWidgets.QWidget()
        self.pageOrder.setObjectName("pageOrder")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageOrder)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.orders = QtWidgets.QLabel(self.pageOrder)
        self.orders.setObjectName("orders")
        self.verticalLayout_4.addWidget(self.orders)
        self.tabs.addWidget(self.pageOrder)
        self.pageSale = QtWidgets.QWidget()
        self.pageSale.setObjectName("pageSale")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pageSale)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sales = QtWidgets.QLabel(self.pageSale)
        self.sales.setObjectName("sales")
        self.verticalLayout_6.addWidget(self.sales)
        self.tabs.addWidget(self.pageSale)
        self.pageAccount = QtWidgets.QWidget()
        self.pageAccount.setObjectName("pageAccount")
        self.acc = QtWidgets.QLabel(self.pageAccount)
        self.acc.setGeometry(QtCore.QRect(9, 9, 16, 16))
        self.acc.setObjectName("acc")
        self.tabs.addWidget(self.pageAccount)
        self.horizontalLayout.addWidget(self.tabs)
        Cashier.setCentralWidget(self.centralwidget)

        self.retranslateUi(Cashier)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Cashier)

    def retranslateUi(self, Cashier):
        _translate = QtCore.QCoreApplication.translate
        Cashier.setWindowTitle(_translate("Cashier", "MainWindow"))
        self.JJelevate_text.setText(_translate("Cashier", "J & J ELEVATE"))
        self.btnDashboard.setText(_translate("Cashier", " Dashboard"))
        self.btnInventory.setText(_translate("Cashier", "Inventory"))
        self.btnOrders.setText(_translate("Cashier", " Orders"))
        self.btnSales.setText(_translate("Cashier", "  Sales"))
        self.btnAccount.setText(_translate("Cashier", " Account"))
        self.btnLogout.setText(_translate("Cashier", "Log out"))
        self.realdateday.setText(_translate("Cashier", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">April 26, 2025</span><span style=\" font-size:20pt; font-weight:600;\"><br/></span><span style=\" font-size:14pt; font-weight:600;\">Monday</span></p></body></html>"))
        self.realtime.setText(_translate("Cashier", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">12:00:00 PM</span></p></body></html>"))
        self.label.setText(_translate("Cashier", "800,000"))
        self.label_5.setText(_translate("Cashier", "Today’s Sales"))
        self.label_12.setText(_translate("Cashier", "300"))
        self.label_7.setText(_translate("Cashier", "Today\'s Total Orders"))
        self.label_19.setText(_translate("Cashier", "20000"))
        self.label_14.setText(_translate("Cashier", "Today’s Revenue"))
        self.label_21.setText(_translate("Cashier", "Best Sellers"))
        self.ViewSalesbtn.setText(_translate("Cashier", "View Sales Report"))
        self.inventorylabel.setText(_translate("Cashier", "Inventory"))
        self.lowstock.setText(_translate("Cashier", "Low in Stock"))
        self.label_24.setText(_translate("Cashier", "4 items"))
        self.label_25.setText(_translate("Cashier", "Warning! These items are low of stock."))
        self.label_22.setText(_translate("Cashier", "Product Name"))
        self.label_28.setText(_translate("Cashier", "ONLY 5 LEFT"))
        self.label_27.setText(_translate("Cashier", "Product Name"))
        self.label_29.setText(_translate("Cashier", "ONLY 5 LEFT"))
        self.label_23.setText(_translate("Cashier", "Product Name"))
        self.label_30.setText(_translate("Cashier", "ONLY 5 LEFT"))
        self.label_26.setText(_translate("Cashier", "Product Name"))
        self.label_31.setText(_translate("Cashier", "ONLY 5 LEFT"))
        self.ViewSalesbtn_2.setText(_translate("Cashier", "View More in Inventory"))
        self.inv.setText(_translate("Cashier", "inventory dae"))
        self.orders.setText(_translate("Cashier", "orders dae"))
        self.sales.setText(_translate("Cashier", "sales"))
        self.acc.setText(_translate("Cashier", "acc"))
